# site settings
title: Haynes Effects | Positional guitar pedals
subtitle: 2020
email: effects@johnhayn.es
description:  Positional guitar pedals
baseurl: "/hayneseffects" # the subpath of your site, e.g. /blog
url: hayneseffects.com # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 
permalink: /:title/

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url: 
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed

# sitemap
url: "https://hayneseffects.com" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap